version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: chai
    versions:
    - 4.2.0
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: solidity-coverage
    versions:
    - 0.7.14
    - 0.7.15
